# Generated by Django 4.1.3 on 2023-02-09 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_notes_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.category'),
        ),
    ]
