# Generated by Django 4.1.3 on 2023-02-18 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_variant_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cat_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='notes',
            name='pro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.product'),
        ),
        migrations.DeleteModel(
            name='Variant',
        ),
    ]
