# Generated by Django 4.1.7 on 2023-02-27 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productspacefiacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spaceficationname', models.CharField(max_length=50, null=True)),
                ('spaceficationvalue', models.CharField(max_length=50, null=True)),
                ('productname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.product')),
            ],
        ),
    ]
