# Generated by Django 4.1.7 on 2023-03-16 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spacename',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spacname', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Spacevalue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spacevalue', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Productspecifiy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.CharField(max_length=120)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.spacename')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.spacevalue')),
            ],
        ),
    ]
