# Generated by Django 4.1.7 on 2023-04-06 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_spacename_spacevalue_productspecifiy'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='desc',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='short',
            field=models.TextField(null=True),
        ),
    ]
