# Generated by Django 4.1.7 on 2023-04-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_product_desc_product_short'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, null=True)),
                ('email', models.CharField(max_length=120, null=True)),
                ('phone', models.CharField(max_length=120, null=True)),
                ('companyname', models.CharField(max_length=120, null=True)),
                ('requirment', models.CharField(max_length=120, null=True)),
                ('enquiry', models.CharField(max_length=120, null=True)),
            ],
        ),
    ]
