# Generated by Django 4.1.7 on 2023-04-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_fileupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(null=True)),
                ('img', models.ImageField(upload_to='image')),
                ('name', models.CharField(max_length=80, null=True)),
                ('designation', models.CharField(max_length=80, null=True)),
            ],
        ),
    ]
