# Generated by Django 4.1.7 on 2023-05-11 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_dp_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='crypto_currency_charges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_name', models.CharField(blank=True, max_length=128, null=True)),
                ('charges', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'crypto_currency_charges',
            },
        ),
    ]
