# Generated by Django 4.1.7 on 2023-05-11 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_crypto_currency_charges'),
    ]

    operations = [
        migrations.CreateModel(
            name='dp_add_fund_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_amount', models.CharField(blank=True, max_length=128, null=True)),
                ('referenceNo', models.CharField(blank=True, max_length=128, null=True)),
                ('username', models.CharField(blank=True, max_length=128, null=True)),
                ('useremail', models.CharField(blank=True, max_length=128, null=True)),
                ('tdate', models.CharField(blank=True, max_length=128, null=True)),
                ('processing_fee', models.CharField(blank=True, max_length=128, null=True)),
                ('method', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
    ]
