# Generated by Django 4.1.7 on 2023-07-23 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_delete_crypto_currency_charges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='siteengineerimg',
            field=models.ImageField(null=True, upload_to='blog'),
        ),
    ]
