# Generated by Django 4.1.7 on 2023-07-23 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_comment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='img',
        ),
    ]
