# Generated by Django 4.1.7 on 2023-07-23 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_comment_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.blog'),
        ),
        migrations.DeleteModel(
            name='Productspecifiy',
        ),
        migrations.DeleteModel(
            name='Spacename',
        ),
        migrations.DeleteModel(
            name='Spacevalue',
        ),
    ]
