# Generated by Django 4.1.7 on 2023-07-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_comment_blog_delete_productspecifiy_delete_spacename_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(upload_to='blog')),
                ('slider', models.ImageField(upload_to='blog')),
                ('img', models.ImageField(upload_to='blog')),
                ('content', models.TextField(max_length=80, null=True)),
                ('content1', models.TextField(max_length=80, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
