# Generated by Django 4.1.7 on 2023-07-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='des',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='engineerdesc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='engineerimg',
            field=models.ImageField(null=True, upload_to='blog'),
        ),
        migrations.AddField(
            model_name='about',
            name='name',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
