# Generated by Django 4.1.7 on 2023-07-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_about_des_about_engineerdesc_about_engineerimg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, null=True)),
                ('des', models.CharField(max_length=80, null=True)),
                ('engineerimg', models.ImageField(null=True, upload_to='blog')),
                ('engineerdesc', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='about',
            name='des',
        ),
        migrations.RemoveField(
            model_name='about',
            name='engineerdesc',
        ),
        migrations.RemoveField(
            model_name='about',
            name='engineerimg',
        ),
        migrations.RemoveField(
            model_name='about',
            name='name',
        ),
    ]
