# Generated by Django 4.1.7 on 2023-07-23 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_slide_remove_about_des_remove_about_engineerdesc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, null=True)),
                ('des', models.CharField(max_length=80, null=True)),
                ('engineerimg', models.ImageField(null=True, upload_to='blog')),
                ('engineerdesc', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
