# Generated by Django 4.1.7 on 2023-07-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_remove_about_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='content1',
            field=models.TextField(null=True),
        ),
    ]
