# Generated by Django 4.1.7 on 2023-07-23 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_about_content2_about_content3_about_img1_about_img2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='content',
        ),
    ]
