# Generated by Django 4.1.7 on 2023-07-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_remove_about_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('silder', models.ImageField(upload_to='blog')),
            ],
        ),
        migrations.RemoveField(
            model_name='about',
            name='banner',
        ),
    ]
