# Generated by Django 4.1.7 on 2023-07-24 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_slider_remove_about_banner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slider',
        ),
        migrations.AddField(
            model_name='about',
            name='status',
            field=models.CharField(choices=[('1', 'Active'), ('2', 'Inactive')], default='2', max_length=1),
        ),
    ]
