# Generated by Django 4.1.7 on 2023-07-25 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='email',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='website',
        ),
    ]
